### ISSUE TITLE
List returns error "cannot allocate memory"?

### ISSUE THREAD

**Issue by fd0** [pkg/xattr#35]
Hi,

a user of [restic](https://restic.net) reported that they get the error `cannot allocate memory`, running restic on Linux (CentOS 7) on amd64 [here](https://github.com/restic/restic/pull/1719#issuecomment-427053724).

Do you maybe have any idea where this comes from? Why would `xattr.List()` return this error?

Thank you very much for your work!

**Comment by ifelsefi** [comment]
Let me know if I can do anything to troubleshoot.

**Comment by kuba--** [comment]
@fd0 - I'll take a look.  Right now we use `"golang.org/x/sys/unix"` (instead of syscalls), so maybe there is something....

**Comment by fd0** [comment]
@kuba-- thanks! I find this error very odd, the machine @ifelsefi used seemed to have enough free memory available, and usually Go panics instead of returning an error when no memory could be allocated... I'm a bit puzzled.

For the record, the commit of `xattr` in question should be `v0.2.3` (1d7b7ffe7c46974a836eb583b7452f22de1c18cf).

**Comment by fd0** [comment]
@kuba-- thanks for the hints. @ifelsefi is the user in question and he's now running the latest version of restic which uses 0.3.1. We'll see what he reports. If it persists, I'd like him to run restic on just a single file, when that works out, we can e.g. use `strace` to see what's going on between the program and the kernel.

What I find odd is that in all cases where I had Go programs which were unable to allocate enough memory, they panic instead of returning an error (especially whith `make([]byte, n)`)...

**Comment by davecheney** [comment]
The error is likely defined here, https://golang.org/src/syscall/zerrors_darwin_arm64.go#L1306

**Comment by kuba--** [comment]
@davecheney - the issue was encountered on linux, so most likely it's because `sysAlloc` returned `nil`:
https://github.com/golang/go/blob/77f9b2728eb08456899e6500328e00ec4829dddf/src/runtime/mem_linux.go#L21

https://github.com/golang/go/blob/4c1c839a3d2270d846f5a6d1cd1287e8560f0265/src/runtime/malloc.go#L1189
or
https://github.com/golang/go/blob/415e948eaea05930b2a16bab6af9e38b24e8414b/src/runtime/mheap.go#L1673

And because it was xattr + rustic it could be any place where errno is `ENOMEM`, most likely from mmap:
https://github.com/golang/go/blob/77f9b2728eb08456899e6500328e00ec4829dddf/src/runtime/mem_linux.go#L164

**Comment by kuba--** [comment]
@fd0 @ifelsefi - shall I close it? Have you had a time to investigate and/or check the latest version?

**Comment by fd0** [comment]
Ah, yes, @ifelsefi reproduced the issue while running strace:
```
[pid  4640] listxattr("/[...].png", 0x1049ef0, 0) = -1 ENOMEM (Cannot allocate emory)
```

This looks like it's just `ENOMEM` returned from the kernel, so in my opinion this library does the right thing. Sorry for the noise and thanks for the support!
